const courseList = [
    {
        playNum:2048,
        likesNum:1024,
        isHover:false,
        productName:"Kwun-B33H",router:"/course/1",
        courseId:1,
        date:"2023-07-25",
        courseTitle:"course.courseList[0].courseTitle",
        desc:"course.courseList[0].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-01-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/2",
        courseId:2,
        date:"2023-07-25",
        courseTitle:"course.courseList[1].courseTitle",
        desc:"course.courseList[1].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-02-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/3",
        courseId:3,
        date:"2023-07-25",
        courseTitle:"course.courseList[2].courseTitle",
        desc:"course.courseList[2].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-03-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/4",
        courseId:4,
        date:"2023-07-25",
        courseTitle:"course.courseList[3].courseTitle",
        desc:"course.courseList[3].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-04-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/5",
        courseId:5,
        date:"2023-07-25",
        courseTitle:"course.courseList[4].courseTitle",
        desc:"course.courseList[4].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-05-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/6",
        courseId:6,
        date:"2023-07-25",
        courseTitle:"course.courseList[5].courseTitle",
        desc:"course.courseList[5].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-06-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/7",
        courseId:7,
        date:"2023-07-25",
        courseTitle:"course.courseList[6].courseTitle",
        desc:"course.courseList[6].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-07-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/8",
        courseId:8,
        date:"2023-07-25",
        courseTitle:"course.courseList[7].courseTitle",
        desc:"course.courseList[7].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-08-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/9",
        courseId:9,
        date:"2023-07-25",
        courseTitle:"course.courseList[8].courseTitle",
        desc:"course.courseList[8].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-09-cover.jpg"
    },
    {
        likesNum:1024,
        playNum:2048,
        isHover:false,
        productName:"Kwun-B33H",
        router:"/course/10",
        courseId:10,
        date:"2023-07-25",
        courseTitle:"course.courseList[9].courseTitle",
        desc:"course.courseList[9].desc",
        imgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-10-cover.jpg"
    },
]

export default {
    courseList
}
