const getRandomMargin = () => {
    const maxMargin = 380; // 设置最大的margin-top值，根据实际需要进行调整
    let randomMargin = Math.floor(Math.random() * maxMargin);
    return `${randomMargin}px`;
};

const courseInfoList =
    [
    {
        title:"course.courseInfoList[0].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-01-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-01.mp4",
        desc:"course.courseInfoList[0].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[0].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[0].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[0].tag[0].name",value:1},
            {name:"course.courseInfoList[0].tag[1].name",value:2},
            {name:"course.courseInfoList[0].tag[2].name",value:3},
        ],
        directory:[
            {
                title:"course.courseInfoList[0].directory[0].title",videoUrl:"https://file.kwunphi.com/kwunphi/video/en/b30en036d47030c394507a036b5e0da490ad7.mp4",
                previewImgUrl:"https://file.kwunphi.com/kwunphi/poster/en/b30en036d47030c394507a036b5e0da490ad7.jpg",
                duration:"course.courseInfoList[0].directory[0].duration",
            },
            {
                title:"course.courseInfoList[0].directory[1].title",videoUrl:"https://file.kwunphi.com/kwunphi/video/zh/b30z21d0342270be4c8cb461f540de5aa9a9.mp4",
                previewImgUrl:"https://file.kwunphi.com/kwunphi/poster/zh/b30z21d0342270be4c8cb461f540de5aa9a9.jpg",
                duration:"course.courseInfoList[0].directory[1].duration",
            },
            {
                title:"course.courseInfoList[0].directory[2].title",videoUrl:"https://file.kwunphi.com/kwunphi/video/zh/b20z101fd99bbb464235a64f1719ebaa4105.mp4",
                previewImgUrl:"https://file.kwunphi.com/kwunphi/poster/zh/b20z101fd99bbb464235a64f1719ebaa4105.jpg",
                duration:"course.courseInfoList[0].directory[2].duration",
            },
        ],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[0].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[0].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[1].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-02-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-02.mp4",
        desc:"course.courseInfoList[1].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[2].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-03-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-03.mp4",
        desc:"course.courseInfoList[2].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[2].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[2].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[3].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-04-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-04.mp4",
        desc:"course.courseInfoList[3].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[4].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-05-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-05.mp4",
        desc:"course.courseInfoList[4].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[5].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-06-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-06.mp4",
        desc:"course.courseInfoList[5].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[6].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-07-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-07.mp4",
        desc:"course.courseInfoList[6].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[7].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-08-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-08.mp4",
        desc:"course.courseInfoList[7].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[8].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-09-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-09.mp4",
        desc:"course.courseInfoList[8].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
    {
        title:"course.courseInfoList[9].title",
        volumePlayback:256,
        commentsNumber:2522,
        date:"2023-07-25",
        previewImgUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-10-cover.jpg",
        videoUrl:"https://file.kwunphi.com/kwunphi4/videos/course/course-10.mp4",
        desc:"course.courseInfoList[9].desc",
        playing:false,
        viewersNumber:256,
        onlineViewersNumber:256,
        likesNum:256,
        coinNum:1222,
        collection:2555,
        forward:30,
        barrageSwitch:false,
        barrageSettings:{
            barragePlaybackSpeed:2,
        },
        barrage:[
            { name: "course.courseInfoList[1].barrage[0].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
            { name: "course.courseInfoList[1].barrage[1].name", likeNum: 26, marginTop: getRandomMargin(),date:"07-11 00:02" ,time:"00:22"},
        ],
        tag:[
            {name:"course.courseInfoList[1].tag[0].name",value:1},
            {name:"course.courseInfoList[1].tag[1].name",value:2},
            {name:"course.courseInfoList[1].tag[2].name",value:3},
        ],
        directory:[],
        comments:[
            {
                avatar:"https://www.kwunphi.com/_nuxt/img/logo1.6568f30.png",
                avatarPackage:"https://i2.hdslb.com/bfs/face/971b69742c60b93225d38eb4c99fc382e2e5eb44.png@240w_240h_!web-avatar-comment.webp",
                isTop:true,
                userName:"course.courseInfoList[1].comments[0].userName",
                grade:"6",
                identity:"up",
                date:"2023-07-11 12:00",
                likeNum:256,
                expandReplies:false,
                commentContent:"course.courseInfoList[1].comments[0].commentContent",
                subComments:[]
            },
        ]
    },
]


//章节目录
/*            {title:"入门案例，堒-如何跟换零件",videoUrl:"https://file.kwunphi.com/kwunphi/video/en/b30en036d47030c394507a036b5e0da490ad7.mp4",
                previewImgUrl:"https://file.kwunphi.com/kwunphi/poster/en/b30en036d47030c394507a036b5e0da490ad7.jpg",
                duration:"40分钟",
            },
            {title:"入门案例，堒-如何跟换零件",videoUrl:"https://file.kwunphi.com/kwunphi/video/zh/b30z21d0342270be4c8cb461f540de5aa9a9.mp4",
                previewImgUrl:"https://file.kwunphi.com/kwunphi/poster/zh/b30z21d0342270be4c8cb461f540de5aa9a9.jpg",
                duration:"20分钟",
            },
            {title:"入门案例，堒-如何跟换零件",videoUrl:"https://file.kwunphi.com/kwunphi/video/zh/b20z101fd99bbb464235a64f1719ebaa4105.mp4",
                previewImgUrl:"https://file.kwunphi.com/kwunphi/poster/zh/b20z101fd99bbb464235a64f1719ebaa4105.jpg",
                duration:"40分钟",
            },*/

export default courseInfoList
