const productList = [
/*    {
        //产品标题
        productTitle:"Kwun-B63G",
        //产品名称
        productName:"Kwun-B63G",
        productId: 1,
        specsRouter:"/specs/Kwun-B63G",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B63G",
        productDesc:"productSpecs.Kwun-B63G.productDesc",
        downloadProductSpecsUrl:"https://file.kwunphi.com/kwunphi/files/specification/Kwun-B63G-%E4%BF%A1%E6%81%AF%E5%8D%95%E9%A1%B5.pdf?r=aae7a2b43d350509cfd483b48037c7ba",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"https://file.kwunphi.com/kwunphi/files/firstuseguide/Kwun-B32H-%E9%A6%96%E6%AC%A1%E4%BD%BF%E7%94%A8%E5%BF%AB%E9%80%9F%E6%8C%87%E5%BC%95.pdf",
                router:"/guide/Kwun-B63G",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"https://file.kwunphi.com/kwunphi/files/instructions_before_use/%E5%A0%92%E4%BA%A7%E5%93%81%E4%BD%BF%E7%94%A8%E5%89%8D%E9%A1%BB%E7%9F%A5.pdf?r=5ca577ba9a4ca0cd5687b485970f58da",
                router:"/instructions-before-use/Kwun-B63G",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"https://file.kwunphi.com/kwunphi/files/manual/Kwun-B63G-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E4%B9%A6.pdf?r=2a10beb8fdb967b90cfea3a32ac08def",
                router:"/instruction-manual/Kwun-B63G",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],

        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B63G.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B63G.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B63G.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B63G.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B63G.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B63G.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B63G.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B63G.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B63G.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]


    },
    {
        //产品标题
        productTitle:"Kwun-B62G",
        //产品名称
        productName:"Kwun-B62G",
        productId: 1,
        specsRouter:"/specs/Kwun-B62G",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B62G",
        productDesc:"productSpecs.Kwun-B62G.productDesc",
        downloadProductSpecsUrl:"https://file.kwunphi.com/kwunphi/files/specification/Kwun-B62G-%E4%BF%A1%E6%81%AF%E5%8D%95%E9%A1%B5.pdf?r=aae7a2b43d350509cfd483b48037c7ba",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"https://file.kwunphi.com/kwunphi/files/firstuseguide/Kwun-B32H-%E9%A6%96%E6%AC%A1%E4%BD%BF%E7%94%A8%E5%BF%AB%E9%80%9F%E6%8C%87%E5%BC%95.pdf",
                router:"/guide/Kwun-B62G",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"https://file.kwunphi.com/kwunphi/files/instructions_before_use/%E5%A0%92%E4%BA%A7%E5%93%81%E4%BD%BF%E7%94%A8%E5%89%8D%E9%A1%BB%E7%9F%A5.pdf?r=5ca577ba9a4ca0cd5687b485970f58da",
                router:"/instructions-before-use/Kwun-B62G",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"https://file.kwunphi.com/kwunphi/files/manual/Kwun-B62G-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E4%B9%A6.pdf?r=2a10beb8fdb967b90cfea3a32ac08def",
                router:"/instruction-manual/Kwun-B62G",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],

        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B62G.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B62G.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B62G.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B62G.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B62G.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B62G.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B62G.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B62G.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B62G.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]


    },*/
    {
        //产品标题
        productTitle:"Kwun-B33H",
        //产品名称
        productName:"Kwun-B33H",
        productId: 1,
        specsRouter:"/specs/Kwun-B33H",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B33H",
        productDesc:"productSpecs.Kwun-B33H.productDesc",
        downloadProductSpecsUrl:"downloads.menuList[2].subMenu[0].content.resource[0].url",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"downloads.menuList[3].subMenu[0].content.resource[0].url",
                router:"/guide/Kwun-B33H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"downloads.menuList[1].subMenu[0].content.resource[0].url",
                router:"/instructions-before-use/Kwun-B33H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"downloads.menuList[4].subMenu[0].content.resource[0].url",
                router:"/instruction-manual/Kwun-B33H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],
        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B33H.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B33H.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B33H.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B33H.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B33H.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B33H.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B33H.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B33H.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B33H.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]
    },
    {
        //产品标题
        productTitle:"Kwun-B32H",
        //产品名称
        productName:"Kwun-B32H",
        productId: 1,
        specsRouter:"/specs/Kwun-B32H",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B32H",
        productDesc:"productSpecs.Kwun-B32H.productDesc",
        downloadProductSpecsUrl:"downloads.menuList[2].subMenu[0].content.resource[1].url",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"downloads.menuList[3].subMenu[0].content.resource[1].url",
                router:"/guide/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"downloads.menuList[1].subMenu[0].content.resource[0].url",
                router:"/instructions-before-use/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"downloads.menuList[4].subMenu[0].content.resource[1].url",
                router:"/instruction-manual/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],
        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B32H.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.bodyWeightWithoutRoller",value:"productSpecs.Kwun-B32H.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B32H.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B32H.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B32H.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B32H.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B32H.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B32H.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B32H.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]


    },
    {
        //产品标题
        productTitle:"Kwun-B32L",
        //产品名称
        productName:"Kwun-B32L",
        productId: 1,
        specsRouter:"/specs/Kwun-B32L",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/32/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B32L",
        productDesc:"productSpecs.Kwun-B32L.productDesc",
        downloadProductSpecsUrl:"downloads.menuList[2].subMenu[0].content.resource[2].url",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"downloads.menuList[3].subMenu[0].content.resource[2].url",
                router:"/guide/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"downloads.menuList[1].subMenu[0].content.resource[0].url",
                router:"/instructions-before-use/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"downloads.menuList[4].subMenu[0].content.resource[2].url",
                router:"/instruction-manual/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],
        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B32L.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B32L.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B32L.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B32L.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B32L.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B32L.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B32L.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B32L.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B32L.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]


    },
    {
        //产品标题
        productTitle:"Kwun-B22H",
        //产品名称
        productName:"Kwun-B22H",
        productId: 1,
        specsRouter:"/specs/Kwun-B22H",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B22H",
        productDesc:"productSpecs.Kwun-B22H.productDesc",
        downloadProductSpecsUrl:"downloads.menuList[2].subMenu[0].content.resource[3].url",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"downloads.menuList[3].subMenu[0].content.resource[3].url",
                router:"/guide/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"downloads.menuList[1].subMenu[0].content.resource[0].url",
                router:"/instructions-before-use/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"downloads.menuList[4].subMenu[0].content.resource[3].url",
                router:"/instruction-manual/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],
        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B22H.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B22H.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B22H.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B22H.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B22H.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]


    },
    {
        //产品标题
        productTitle:"Kwun-B22L",
        //产品名称
        productName:"Kwun-B22L",
        productId: 1,
        specsRouter:"/specs/Kwun-B22L",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/02.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/03.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/04.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/05.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/06.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/06.png",
        ],
        purchaseRouter: "/purchase/Kwun-B22L",
        productDesc:"productSpecs.Kwun-B22L.productDesc",
        downloadProductSpecsUrl:"downloads.menuList[2].subMenu[0].content.resource[4].url",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"downloads.menuList[3].subMenu[0].content.resource[4].url",
                router:"/guide/Kwun-B22L",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"downloads.menuList[1].subMenu[0].content.resource[0].url",
                router:"/instructions-before-use/Kwun-B22L",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"downloads.menuList[4].subMenu[0].content.resource[4].url",
                router:"/instruction-manual/Kwun-B22L",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],
        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B22L.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B22L.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B22L.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B22L.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B22L.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B22L.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B22L.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B22L.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B22L.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]
    },
    {
        //产品标题
        productTitle:"Kwun-B11L",
        //产品名称
        productName:"Kwun-B11L",
        productId: 1,
        specsRouter:"/specs/Kwun-B11L",//产品参数路径
        productBanner: [
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/1.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/2.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/3.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/4.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/5.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/6.png",
            "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/7.png",
        ],
        purchaseRouter: "/purchase/Kwun-B11L",
        productDesc:"productSpecs.Kwun-B11L.productDesc",
        downloadProductSpecsUrl:"downloads.menuList[2].subMenu[0].content.resource[5].url",
        link:[
            {name:"productSpecs.downloadResource.quickGuide",
                downLoadUrl:"downloads.menuList[3].subMenu[0].content.resource[5].url",
                router:"/guide/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/pdf.svg"
            },
            {name:"productSpecs.downloadResource.beforeUse",
                downLoadUrl:"downloads.menuList[1].subMenu[0].content.resource[0].url",
                router:"/instructions-before-use/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/use.svg"
            },
            {name:"productSpecs.downloadResource.instructionManual",
                downLoadUrl:"downloads.menuList[4].subMenu[0].content.resource[5].url",
                router:"/instruction-manual/Kwun-B32H",
                icon:"https://file.kwunphi.com/kwunphi4/images/commons/instruction-manual.svg"
            },
        ],
        specs:[
            {
                title:"productSpecs.standardParameters.title",
                parameters:[
                    {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B11L.shape.bodySizeWithoutRoller"},
                    {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B11L.shape.bodyWeightWithoutRoller"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B11L.abilityToClean.cleaningEfficiency"},
                    {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B11L.lifeAndEndurance.enduranceTime"},
                    {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B11L.lifeAndEndurance.chargingTime"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B11L.standardParameters.dryPVPanelAngle"},
                    {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B11L.standardParameters.wetPVPanelAngle"},
                ]
            },
            {
                title:"",
                parameters:[
                    {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B11L.lifeAndEndurance.designLife"},
                    {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B11L.lifeAndEndurance.warrantyPeriod"},
                ]
            },
        ]


    },
]
const productMap = new Map()
productList.forEach((product)=>{
    productMap.set(product.productName,product)
})

export default productMap
