//产品购买信息
const productList = [
    {
        productName: "Kwun-B63G",
        productModel:"Kwun-B63G",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/07.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/07.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B33H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B63G.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B63G.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B63G.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B63G.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B63G.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B63G.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B63G.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B63G.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B63G.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B62G",
        productModel:"Kwun-B62G",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/06.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/07.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/63/bg-white/07.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B33H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B62G.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B62G.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B62G.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B62G.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B62G.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B62G.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B62G.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B62G.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B62G.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B33H",
        productModel:"Kwun-B33H",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B33H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B33H.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B33H.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B33H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B33H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B33H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B33H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B33H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B33H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B33H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[
/*                {PackageTitle:"Kwun-B33H 无忧套装1",
                    imgUrl:"https://stormsend1.djicdn.com/tpc/uploads/carousel/image/77aeb9c665da87af34ece875d068deb6@ultra.jpg",
                    dotImgUrl:"https://stormsend1.djicdn.com/tpc/uploads/carousel/image/af06e456c234671d3ac890c4c7c7950f@ultra.jpg",
                    isSelected: false,
                    quantity:0,
                    price:138888,
                    desc:"额外包含 DJI Mic 无线收音系统，支持 250 米传输距离，抗干扰能力强，在闹市、商场或办公室，都能稳定收音，轻松玩转直播和 vlog 拍摄。",
                    content:"额外包含 DJI Mic 无线收音系统，支持 250 米传输距离，抗干扰能力强，在闹市、商场或办公室，都能稳定收音，轻松玩转直播和 vlog 拍摄。"
                },*/
            ],
            accessories:[
/*                {
                    accessoriesName:"Kwun-B33H 无忧套装1",
                    imgUrl:"https://stormsend1.djicdn.com/tpc/uploads/spu/cover/dbacd1aabeb65ada84e56edb6e2f731f@small.png",
                    isSelected: false,
                    quantity:0,
                    price:13888,
                    desc:"额外包含 DJI Mic 无线收音系统，支持 250 米传输距离，抗干扰能力强，在闹市、商场或办公室，都能稳定收音，轻松玩转直播和 vlog 拍摄。",
                    content:"额外包含 DJI Mic 无线收音系统，支持 250 米传输距离，抗干扰能力强，在闹市、商场或办公室，都能稳定收音，轻松玩转直播和 vlog 拍摄。",
                    details:{
                        banner:["https://stormsend1.djicdn.com/tpc/uploads/photos/35430/large_0b8dfe16-19c5-4319-ae24-bc94f0dbe8cd.jpg",
                            "https://stormsend1.djicdn.com/tpc/uploads/photos/35430/large_0b8dfe16-19c5-4319-ae24-bc94f0dbe8cd.jpg"],
                        productName:"闪迪 microSD 卡 128GB",
                        price:388,
                        intro:"闪迪至尊极速移动 microSDXC UHS-I 存储卡拥有您所需的卓越速度、容量、耐用性和品质，定能捕捉到您冒险旅程中的精彩细节。支持 U3 视频等级，能够配合您的 DJI 怪虫机器人产品使用，帮助您捕捉和分享令人难忘的视频。海量存储高达 128GB。",
                        blips:["128GB 大容量，更长的 4K 视频录制时间","通过官方兼容性测试，适配 DJI 怪虫机器人飞行器。","读取速度高达 160MB/秒，写入速度高达 90MB/秒。","U3 视频等级，4K 视频画质有保障。"],
                    }
                },*/
            ],
        },
    },
    {
        productName: "Kwun-B32H",
        productModel:"Kwun-B32H",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B32H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B32H.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B32H.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B32H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B32H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B32H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B32H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B32H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B32H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B32H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],

        },
    },
    {
        productName: "Kwun-B32L",
        productModel:"Kwun-B32L",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32L.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32L.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B32L.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B32L.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B32L.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B32L.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B32L.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B32L.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B32L.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B32L.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B32L.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B32L.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B22H",
        productModel:"Kwun-B22H",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B22H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B22H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B22H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B22H.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B22H.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B22H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B22H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B22H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B22L",
        productModel:"Kwun-B22L",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B22L.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B22L.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B22L.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B22L.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B22L.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B22H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B22H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B22H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B11L",
        productModel:"Kwun-B11L",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/1.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/1.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/2.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/2.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/3.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/3.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/4.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/4.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/5.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/5.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/6.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/6.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B11L.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B11L.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B11L.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B11L.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B11L.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B11L.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B11L.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B11L.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B11L.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B11L.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B11L.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B11L.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
]


const productMap = new Map()
productList.forEach((product)=>{
    productMap.set(product.productModel,product)
})

export default {
    productList,productMap
}
